import mongoose from "mongoose";
 const schema= new mongoose.Schema({
    sno:{
        type:String,
        required:true,
    },
    roomno:{
        type:String,
        required:true,
    },
    name:{
        type:String,
        required:true,
    },
    date:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    sem:{
        type:String,
        required:true,
    },
    total:{
        type:String,
        required:true,
    },
    caution:{
        type:String,
        required:true,
    },
    mess:{
        type:String,
        required:true,
    },
    rent:{
        type:String,
        required:true,
    },
    others:{
        type:String,
        required:true,
    },
    balance:{
        type:String,
        required:true,
    },
    status:{
        type:String,
        required:true,
        enum:["pending","paid"],
        default:"pending",
    },
 },{timestamps:true})

 export const feespayments = mongoose.model("feesPayments",schema)