import mongoose from "mongoose";
 const schema = new mongoose.Schema({
    sno:{
        type:String,
        required:true,
    },
    roomno:{
        type:String,
        required:true,
    },
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    phno:{
        type:String,
        required:true,
    },
   parentphno:{
        type:String,
        required:true,
    },
    outtime:{
        type:String,
        required:true,
    },
    outtimeap:{
        type:String,
        required:true, 
    },
    intime:{
        type:String,
        required:true,
    },
    intimeap:{
        type:String,
        required:true,
    },
    date:{
        type:String,
        required:true,
    },
    reason:{
        type:String,
        required:true,
    },
    status:{
        type:String,
        enum:["Request","Approved","Decline"],
        default:"Request",
    }
 },{timestamps:true})

export const outpass= mongoose.model("outpass",schema)